/*
 * This file was automatically generated by EvoSuite
 * Wed May 28 21:55:49 GMT 2025
 */

package Projeto;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Projeto.AppDesportiva;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AppDesportiva_ESTest extends AppDesportiva_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SystemInUtil.addInputLine("bh&WGU4L}'X");
      AppDesportiva appDesportiva0 = null;
      try {
        appDesportiva0 = new AppDesportiva("Projeto.AtivDistancia");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      AppDesportiva appDesportiva0 = new AppDesportiva();
      // Undeclared exception!
      try { 
        appDesportiva0.runSimulacao();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      AppDesportiva appDesportiva0 = new AppDesportiva();
      // Undeclared exception!
      try { 
        appDesportiva0.runQueries();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      AppDesportiva appDesportiva0 = new AppDesportiva();
      // Undeclared exception!
      try { 
        appDesportiva0.runInicial();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AppDesportiva appDesportiva0 = null;
      try {
        appDesportiva0 = new AppDesportiva((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      AppDesportiva appDesportiva0 = new AppDesportiva();
      SystemInUtil.addInputLine("0");
      appDesportiva0.runInicial();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      AppDesportiva appDesportiva0 = new AppDesportiva();
      SystemInUtil.addInputLine("0");
      appDesportiva0.runQueries();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      AppDesportiva appDesportiva0 = new AppDesportiva();
      SystemInUtil.addInputLine("0");
      appDesportiva0.runSimulacao();
      // Undeclared exception!
      try { 
        appDesportiva0.runSetup();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      AppDesportiva appDesportiva0 = new AppDesportiva();
      SystemInUtil.addInputLine("0");
      int int0 = appDesportiva0.runSetup();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      AppDesportiva appDesportiva0 = null;
      try {
        appDesportiva0 = new AppDesportiva();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      AppDesportiva appDesportiva0 = new AppDesportiva();
      SystemInUtil.addInputLine("0");
      // Undeclared exception!
      try { 
        appDesportiva0.estatisticaUtilizadorEntreDatas(1856);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      AppDesportiva appDesportiva0 = new AppDesportiva();
      // Undeclared exception!
      try { 
        appDesportiva0.estatisticaEntreDatas(2);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      AppDesportiva appDesportiva0 = null;
      try {
        appDesportiva0 = new AppDesportiva();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }
}
