/*
 * This file was automatically generated by EvoSuite
 * Wed May 28 22:06:46 GMT 2025
 */

package Projeto;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Projeto.Btt;
import Projeto.Ciclismo;
import Projeto.Utilizador;
import Projeto.UtilizadorAmador;
import Projeto.UtilizadorPraticanteOcasional;
import Projeto.UtilizadorProfissional;
import java.time.Clock;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;
import java.time.chrono.MinguoDate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.evosuite.runtime.mock.java.time.MockLocalTime;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.evosuite.runtime.mock.java.time.chrono.MockMinguoDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Btt_ESTest extends Btt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Btt btt0 = new Btt();
      MinguoDate minguoDate0 = MockMinguoDate.now();
      LocalDate localDate0 = MockLocalDate.from(minguoDate0);
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("", "", "", 0, 0, (-1), localDate0, '{');
      Btt btt1 = (Btt)btt0.geraAtividade(utilizadorPraticanteOcasional0, (-1));
      assertEquals(11602.5, btt1.getDistancia(), 0.01);
      assertEquals(0, btt1.getFreqCardiaca());
      assertEquals(0.0, btt1.getFatorAltimetria(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LocalTime localTime0 = MockLocalTime.now();
      Btt btt0 = new Btt((LocalDateTime) null, localTime0, 2, 2, 943.07706568);
      assertEquals(1.05, btt0.getFatorHard(), 0.01);
      
      btt0.setAltimetria(2000.0);
      double double0 = btt0.getFatorHard();
      assertEquals(1.1500000000000001, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(0L);
      Btt btt0 = new Btt(localDateTime0, localTime0, (-1), 0L, 1000.0);
      double double0 = btt0.getFatorHard();
      assertEquals(1.05, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Btt btt0 = new Btt();
      btt0.setProximoCodigo(0);
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional();
      Btt btt1 = (Btt)btt0.geraAtividade(utilizadorPraticanteOcasional0, 451.90529669926);
      assertEquals(0, btt1.getFreqCardiaca());
      assertEquals(2.25485782935E10, btt1.getDistancia(), 0.01);
      assertEquals(0.0, btt1.getAltimetria(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Btt btt0 = new Btt();
      btt0.setProximoCodigo((-4256));
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador();
      Btt btt1 = (Btt)btt0.geraAtividade(utilizadorAmador0, 2562.8101155227505);
      assertEquals(2.25485782935E10, btt1.getDistancia(), 0.01);
      assertEquals(0.0, btt1.getFatorAltimetria(), 0.01);
      assertEquals(0, btt1.getFreqCardiaca());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDateTime localDateTime0 = MockLocalDateTime.now(clock0);
      LocalTime localTime0 = MockLocalTime.now(clock0);
      Btt btt0 = new Btt(localDateTime0, localTime0, 3290, 3290, 3290);
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador();
      double double0 = btt0.consumoCalorias(utilizadorAmador0);
      assertEquals(1.2500000000000002, btt0.getFatorHard(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(1985);
      LocalDateTime localDateTime0 = MockLocalDateTime.now((ZoneId) zoneOffset0);
      LocalTime localTime0 = MockLocalTime.now((ZoneId) zoneOffset0);
      Btt btt0 = new Btt(localDateTime0, localTime0, 1334, 10.0, 1985);
      Period period0 = Period.of(1985, (-125), 1985);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0, (ZoneId) zoneOffset0);
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador("Ms", "z-a", "z-a", (-1037), 1985, 1334, localDate0, '[');
      double double0 = btt0.consumoCalorias(utilizadorAmador0);
      assertEquals(10593.51254159435, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Btt btt0 = new Btt();
      btt0.setFreqCardiaca(6540);
      btt0.setAltimetria(2403);
      UtilizadorProfissional utilizadorProfissional0 = new UtilizadorProfissional();
      LocalTime localTime0 = MockLocalTime.now();
      btt0.setTempo(localTime0);
      System.setCurrentTimeMillis(730);
      double double0 = btt0.consumoCalorias(utilizadorProfissional0);
      assertEquals(1.2500000000000002, btt0.getFatorHard(), 0.01);
      assertEquals((-1741.1658897569448), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LocalTime localTime0 = MockLocalTime.of(10, 0);
      Btt btt0 = new Btt((LocalDateTime) null, localTime0, 1, 0, 1);
      // Undeclared exception!
      try { 
        btt0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(0L);
      Btt btt0 = new Btt(localDateTime0, localTime0, (-1), 0L, 1000.0);
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("", "Atividade\nId: 1\nData e hora: 14/02/2014 20:21:21\nDura\u00E7ao: 00:00\nFrequencia Cardiaca: -1 bpm\nDistancia: 0.0 metros\nAltimetria: 1000.0 metros\nTipo de atividade: BTT\n", "", (-3047), 2144930266, 3751, (LocalDate) null, 't');
      // Undeclared exception!
      try { 
        btt0.geraAtividade(utilizadorPraticanteOcasional0, 0.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Utilizador", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Btt btt0 = new Btt();
      btt0.setTempo((LocalTime) null);
      Object object0 = btt0.clone();
      // Undeclared exception!
      try { 
        btt0.equals(object0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Btt btt0 = new Btt();
      // Undeclared exception!
      try { 
        btt0.consumoCalorias((Utilizador) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Btt", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Btt btt0 = null;
      try {
        btt0 = new Btt((Btt) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Btt btt0 = new Btt();
      double double0 = btt0.getFatorHard();
      assertEquals(1.05, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Btt btt0 = new Btt();
      Btt btt1 = new Btt(btt0);
      boolean boolean0 = btt0.equals(btt1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Btt btt0 = new Btt();
      boolean boolean0 = btt0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Btt btt0 = new Btt();
      boolean boolean0 = btt0.equals(btt0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Btt btt0 = new Btt();
      Ciclismo ciclismo0 = new Ciclismo();
      boolean boolean0 = btt0.equals(ciclismo0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LocalTime localTime0 = MockLocalTime.now();
      Btt btt0 = new Btt((LocalDateTime) null, localTime0, 2144657411, 2144657411, 2144657411);
      double double0 = btt0.getFatorHard();
      assertEquals(1.2500000000000002, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Btt btt0 = new Btt();
      UtilizadorProfissional utilizadorProfissional0 = new UtilizadorProfissional();
      // Undeclared exception!
      try { 
        btt0.consumoCalorias(utilizadorProfissional0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("Projeto.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Btt btt0 = new Btt();
      String string0 = btt0.toString();
      assertEquals("Atividade\nId: 1\nData e hora: 14/02/2014 20:21:21\nDura\u00E7ao: 00:00\nFrequencia Cardiaca: 0 bpm\nDistancia: 0.0 metros\nAltimetria: 0.0 metros\nTipo de atividade: BTT\n", string0);
  }
}
