/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 04 15:35:16 GMT 2025
 */

package Projeto;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Projeto.Ciclismo;
import Projeto.Utilizador;
import Projeto.UtilizadorAmador;
import Projeto.UtilizadorPraticanteOcasional;
import Projeto.UtilizadorProfissional;
import java.time.Clock;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.evosuite.runtime.mock.java.time.MockLocalTime;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ciclismo_ESTest extends Ciclismo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Ciclismo ciclismo0 = new Ciclismo();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0);
      UtilizadorProfissional utilizadorProfissional0 = new UtilizadorProfissional("oV 95Ke[JVmO", "oV 95Ke[JVmO", "oV 95Ke[JVmO", 2, 0, 0, localDate0, '\'');
      Ciclismo ciclismo1 = (Ciclismo)ciclismo0.geraAtividade(utilizadorProfissional0, 2);
      assertEquals(0, ciclismo1.getFreqCardiaca());
      assertEquals(913.5, ciclismo1.getDistancia(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Ciclismo ciclismo0 = new Ciclismo();
      ciclismo0.setProximoCodigo(0);
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador();
      Ciclismo ciclismo1 = (Ciclismo)ciclismo0.geraAtividade(utilizadorAmador0, 1178L);
      assertEquals(0, ciclismo1.getFreqCardiaca());
      assertEquals(2.25485782935E10, ciclismo1.getDistancia(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Ciclismo ciclismo0 = new Ciclismo();
      ciclismo0.setProximoCodigo((-9));
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador();
      Ciclismo ciclismo1 = (Ciclismo)ciclismo0.geraAtividade(utilizadorAmador0, 1178L);
      assertEquals(2.25485782935E10, ciclismo1.getDistancia(), 0.01);
      assertEquals(0, ciclismo1.getFreqCardiaca());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDateTime localDateTime0 = MockLocalDateTime.now(clock0);
      LocalTime localTime0 = MockLocalTime.now(clock0);
      Ciclismo ciclismo0 = new Ciclismo(localDateTime0, localTime0, 415, 1.15);
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional();
      double double0 = ciclismo0.consumoCalorias(utilizadorPraticanteOcasional0);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDateTime localDateTime0 = MockLocalDateTime.now(clock0);
      LocalTime localTime0 = MockLocalTime.now(clock0);
      Ciclismo ciclismo0 = new Ciclismo(localDateTime0, localTime0, 415, 1.15);
      LocalDate localDate0 = MockLocalDate.now(clock0);
      UtilizadorProfissional utilizadorProfissional0 = new UtilizadorProfissional("\"`7PaV$`d7J", "", "`:WFU Xl}KWqP", 415, 415, (-3649), localDate0, 'H');
      double double0 = ciclismo0.consumoCalorias(utilizadorProfissional0);
      assertEquals(5221.584449869796, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Period period0 = Period.ofWeeks(1);
      IsoChronology isoChronology0 = period0.getChronology();
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(1);
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0, (ZoneId) zoneOffset0);
      Clock clock0 = MockClock.systemDefaultZone();
      LocalTime localTime0 = MockLocalTime.now(clock0);
      LocalDateTime localDateTime0 = MockLocalDateTime.of(localDate0, localTime0);
      Ciclismo ciclismo0 = new Ciclismo(localDateTime0, localTime0, 1, 1);
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("yJL:u`", "Projeto.Ciclismo", "|4o1uS", 1, 395, (-257), localDate0, 'R');
      double double0 = ciclismo0.consumoCalorias(utilizadorPraticanteOcasional0);
      assertEquals((-3637.792154947919), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Ciclismo ciclismo0 = new Ciclismo();
      ciclismo0.setDataRealizacao((LocalDateTime) null);
      // Undeclared exception!
      try { 
        ciclismo0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Ciclismo ciclismo0 = new Ciclismo();
      // Undeclared exception!
      try { 
        ciclismo0.geraAtividade((Utilizador) null, 86400.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Ciclismo", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Ciclismo ciclismo0 = new Ciclismo((LocalDateTime) null, (LocalTime) null, (-563), (-563));
      Ciclismo ciclismo1 = new Ciclismo(ciclismo0);
      // Undeclared exception!
      try { 
        ciclismo1.equals(ciclismo0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Ciclismo ciclismo0 = new Ciclismo();
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador();
      // Undeclared exception!
      try { 
        ciclismo0.consumoCalorias(utilizadorAmador0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("Projeto.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Ciclismo ciclismo0 = null;
      try {
        ciclismo0 = new Ciclismo((Ciclismo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Ciclismo ciclismo0 = new Ciclismo();
      boolean boolean0 = ciclismo0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Ciclismo ciclismo0 = new Ciclismo();
      boolean boolean0 = ciclismo0.equals(ciclismo0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.ofNanoOfDay(0L);
      Ciclismo ciclismo0 = new Ciclismo(localDateTime0, localTime0, 1699, 1699);
      boolean boolean0 = ciclismo0.equals("Atividade\nId: 1\nData e hora: 14/02/2014 20:21:21\nDura\u00E7ao: 00:00\nFrequencia Cardiaca: 1699 bpm\nDistancia: 1699.0 metros\nTipo de atividade: Ciclismo\n");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.ofNanoOfDay(0L);
      Ciclismo ciclismo0 = new Ciclismo(localDateTime0, localTime0, 1699, 1699);
      String string0 = ciclismo0.toString();
      assertEquals("Atividade\nId: 1\nData e hora: 14/02/2014 20:21:21\nDura\u00E7ao: 00:00\nFrequencia Cardiaca: 1699 bpm\nDistancia: 1699.0 metros\nTipo de atividade: Ciclismo\n", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Ciclismo ciclismo0 = new Ciclismo();
      Object object0 = ciclismo0.clone();
      boolean boolean0 = ciclismo0.equals(object0);
      assertTrue(boolean0);
      assertNotSame(object0, ciclismo0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Ciclismo ciclismo0 = new Ciclismo();
      // Undeclared exception!
      try { 
        ciclismo0.consumoCalorias((Utilizador) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Ciclismo", e);
      }
  }
}
