/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 04 15:38:11 GMT 2025
 */

package Projeto;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Projeto.Atividade;
import Projeto.Flexoes;
import Projeto.Utilizador;
import Projeto.UtilizadorAmador;
import Projeto.UtilizadorPraticanteOcasional;
import Projeto.UtilizadorProfissional;
import java.time.Clock;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.evosuite.runtime.mock.java.time.MockLocalTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Flexoes_ESTest extends Flexoes_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(666L);
      LocalTime localTime0 = MockLocalTime.now();
      LocalDateTime localDateTime0 = MockLocalDateTime.of(localDate0, localTime0);
      Flexoes flexoes0 = new Flexoes(localDateTime0, localTime0, 1073, 0);
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("", "", "Atividade\nId: 1\nData e hora: 29/10/1971 20:21:21\nDura\u00E7ao: 20:21:21.320\nFrequencia Cardiaca: 1073 bpm\nRepeti\u00E7oes: 0\nTipo de atividade: Flex\u00F5es\n", 0, 1073, 1073, localDate0, 'c');
      Flexoes flexoes1 = (Flexoes)flexoes0.geraAtividade(utilizadorPraticanteOcasional0, 224.30283212);
      assertEquals(250, flexoes1.getRepeticoes());
      assertEquals(0, flexoes1.getFreqCardiaca());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Flexoes flexoes0 = new Flexoes();
      LocalDate localDate0 = MockLocalDate.now();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("", "", "<{^A~j~Z.9]", 77, 77, 0, localDate0, ']');
      Atividade atividade0 = flexoes0.geraAtividade(utilizadorPraticanteOcasional0, 0);
      assertTrue(atividade0.equals((Object)flexoes0));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHours(0);
      LocalDateTime localDateTime0 = MockLocalDateTime.ofEpochSecond(934L, 0, zoneOffset0);
      LocalTime localTime0 = MockLocalTime.now((ZoneId) zoneOffset0);
      Flexoes flexoes0 = new Flexoes(localDateTime0, localTime0, (-278), 0);
      UtilizadorProfissional utilizadorProfissional0 = new UtilizadorProfissional();
      utilizadorProfissional0.setFreqCardiaca((-278));
      double double0 = flexoes0.consumoCalorias(utilizadorProfissional0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Flexoes flexoes0 = new Flexoes();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional();
      flexoes0.setProximoCodigo(0);
      Atividade atividade0 = flexoes0.geraAtividade(utilizadorPraticanteOcasional0, 0.0);
      assertTrue(atividade0.equals((Object)flexoes0));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Flexoes flexoes0 = new Flexoes();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional();
      flexoes0.setProximoCodigo((-143));
      Flexoes flexoes1 = (Flexoes)flexoes0.geraAtividade(utilizadorPraticanteOcasional0, 2392);
      assertEquals(Integer.MAX_VALUE, flexoes1.getRepeticoes());
      assertEquals(0, flexoes1.getFreqCardiaca());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(666L);
      LocalTime localTime0 = MockLocalTime.now();
      LocalDateTime localDateTime0 = MockLocalDateTime.of(localDate0, localTime0);
      Flexoes flexoes0 = new Flexoes(localDateTime0, localTime0, 1073, 0);
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("", "", "Atividade\nId: 1\nData e hora: 29/10/1971 20:21:21\nDura\u00E7ao: 20:21:21.320\nFrequencia Cardiaca: 1073 bpm\nRepeti\u00E7oes: 0\nTipo de atividade: Flex\u00F5es\n", 0, 1073, 1073, localDate0, 'c');
      double double0 = flexoes0.consumoCalorias(utilizadorPraticanteOcasional0);
      assertEquals(18339.57213867187, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHours(0);
      LocalDateTime localDateTime0 = MockLocalDateTime.ofEpochSecond(934L, 0, zoneOffset0);
      LocalTime localTime0 = MockLocalTime.now((ZoneId) zoneOffset0);
      Flexoes flexoes0 = new Flexoes(localDateTime0, localTime0, (-278), 0);
      UtilizadorProfissional utilizadorProfissional0 = new UtilizadorProfissional();
      System.setCurrentTimeMillis((-278));
      double double0 = flexoes0.consumoCalorias(utilizadorProfissional0);
      assertEquals((-400.75546875), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalTime localTime0 = MockLocalTime.now(clock0);
      Flexoes flexoes0 = new Flexoes((LocalDateTime) null, localTime0, (-1483), (-634));
      // Undeclared exception!
      try { 
        flexoes0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDateTime localDateTime0 = MockLocalDateTime.now(clock0);
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(7L);
      Flexoes flexoes0 = new Flexoes(localDateTime0, localTime0, 0, 209);
      // Undeclared exception!
      try { 
        flexoes0.geraAtividade((Utilizador) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Flexoes", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Flexoes flexoes0 = new Flexoes();
      Flexoes flexoes1 = new Flexoes();
      flexoes1.setTempo((LocalTime) null);
      // Undeclared exception!
      try { 
        flexoes1.equals(flexoes0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Flexoes flexoes0 = new Flexoes();
      // Undeclared exception!
      try { 
        flexoes0.consumoCalorias((Utilizador) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Flexoes", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Flexoes flexoes0 = new Flexoes();
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador("G}lc\"", "", "", 2484, (-2135), 2484, (LocalDate) null, '}');
      // Undeclared exception!
      try { 
        flexoes0.consumoCalorias(utilizadorAmador0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("Projeto.AtivRepeticoes", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Flexoes flexoes0 = null;
      try {
        flexoes0 = new Flexoes((Flexoes) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Flexoes flexoes0 = new Flexoes();
      Object object0 = new Object();
      boolean boolean0 = flexoes0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Flexoes flexoes0 = new Flexoes();
      Flexoes flexoes1 = new Flexoes();
      boolean boolean0 = flexoes1.equals(flexoes0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Flexoes flexoes0 = new Flexoes();
      boolean boolean0 = flexoes0.equals(flexoes0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Flexoes flexoes0 = new Flexoes();
      boolean boolean0 = flexoes0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Flexoes flexoes0 = new Flexoes();
      String string0 = flexoes0.toString();
      assertEquals("Atividade\nId: 1\nData e hora: 14/02/2014 20:21:21\nDura\u00E7ao: 00:00\nFrequencia Cardiaca: 0 bpm\nRepeti\u00E7oes: 0\nTipo de atividade: Flex\u00F5es\n", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Flexoes flexoes0 = new Flexoes();
      Object object0 = flexoes0.clone();
      assertNotSame(object0, flexoes0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Flexoes flexoes0 = new Flexoes();
      Flexoes flexoes1 = new Flexoes(flexoes0);
      assertTrue(flexoes1.equals((Object)flexoes0));
  }
}
