/*
 * This file was automatically generated by EvoSuite
 * Wed May 28 22:03:58 GMT 2025
 */

package Projeto;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Projeto.Menu;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Menu_ESTest extends Menu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[] stringArray0 = new String[1];
      String string0 = "";
      stringArray0[0] = "";
      SystemInUtil.addInputLine("");
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(1, stringArray0.length);
      assertNotNull(menu0);
      
      String string1 = menu0.pedeString("");
      assertEquals((-1), menu0.getOpcao());
      assertEquals(1, stringArray0.length);
      assertEquals("", string1);
      assertNotNull(string1);
      assertTrue(string1.equals((Object)string0));
      
      // Undeclared exception!
      menu0.pedeDataHora("");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "";
      String string0 = "gLi| Y%bl=Cc1pE";
      stringArray0[2] = "";
      String string1 = "";
      stringArray0[3] = "";
      stringArray0[4] = ": ";
      stringArray0[5] = "a^";
      stringArray0[6] = ": ";
      String string2 = "";
      stringArray0[7] = "";
      SystemInUtil.addInputLine(": ");
      stringArray0[8] = "dd/MM/yyyy";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(9, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      try { 
        menu0.pedeDouble(">R}Qq,h!akM_(M");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "";
      stringArray0[2] = "G<M[rE";
      SystemInUtil.addInputLine("\"Uiz\"I~BiaC[og-KQ");
      stringArray0[4] = "";
      stringArray0[5] = "7^0H{X-= F)>V65nhA";
      stringArray0[6] = "pzZT5*tyLs<nU @";
      stringArray0[7] = "";
      stringArray0[8] = "H(1j";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(9, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "p240bSw+KhU)8lE= ";
      stringArray0[1] = "";
      stringArray0[2] = "Inserir uma dura\u00E7\u00E3o no formato horas:minutos ou horas:minutos:segundos";
      stringArray0[3] = "";
      stringArray0[4] = "[fx#dhC]Y;,5C*FI3l!";
      SystemInUtil.addInputLine("dd/MM/yyyy HH:mm:ss");
      stringArray0[5] = "!#DT~";
      stringArray0[6] = "";
      stringArray0[7] = "612Nrvx%?#:b";
      stringArray0[8] = "6=U7=p't[8-g'";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(9, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      try { 
        menu0.pedeInt("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SystemInUtil.addInputLine((String) null);
      SystemInUtil.addInputLine("FQXulY=j:H2t9G827");
      String[] stringArray0 = new String[5];
      stringArray0[0] = "FQXulY=j:H2t9G827";
      stringArray0[1] = "FQXulY=j:H2t9G827";
      stringArray0[2] = "FQXulY=j:H2t9G827";
      stringArray0[3] = "a,";
      stringArray0[4] = "FQXulY=j:H2t9G827";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(5, stringArray0.length);
      assertNotNull(menu0);
      
      String string0 = menu0.pedeString("");
      assertEquals((-1), menu0.getOpcao());
      assertEquals(5, stringArray0.length);
      assertEquals("FQXulY=j:H2t9G827", string0);
      assertNotNull(string0);
      
      int int0 = menu0.getOpcao();
      assertEquals((-1), menu0.getOpcao());
      assertEquals(5, stringArray0.length);
      assertEquals((-1), int0);
      
      // Undeclared exception!
      menu0.pedeTempo("");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(0, stringArray0.length);
      assertNotNull(menu0);
      
      int int0 = menu0.getOpcao();
      assertEquals((-1), menu0.getOpcao());
      assertEquals(0, stringArray0.length);
      assertEquals((-1), int0);
      
      String string0 = "";
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String[] stringArray0 = new String[7];
      String string0 = "&;wb";
      stringArray0[0] = "&;wb";
      stringArray0[1] = "-X";
      stringArray0[2] = "ETPOeSvZ%S)gw";
      stringArray0[3] = "Inserir uma dura\u00E7\u00E3o no formato horas:minutos ou horas:minutos:segundos";
      stringArray0[4] = "b:`6Z.{1";
      stringArray0[5] = "";
      stringArray0[6] = "";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(7, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      try { 
        menu0.pedeInt((String) null);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[7];
      stringArray0[0] = "D(5H0GA1o(hMr?17";
      stringArray0[1] = "hl2=6$f~*:~~q";
      stringArray0[2] = "";
      stringArray0[3] = "W()c";
      stringArray0[4] = "";
      stringArray0[5] = "Inserir um n\u00FAmero";
      stringArray0[6] = "H<C) P|eB'J`\"m[s";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(7, stringArray0.length);
      assertNotNull(menu0);
      
      int int0 = menu0.getOpcao();
      assertEquals((-1), menu0.getOpcao());
      assertEquals(7, stringArray0.length);
      assertEquals((-1), int0);
      
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "iCkt\"{slR2K<-!";
      stringArray0[1] = "-------------\n";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(2, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      try { 
        menu0.pedeString("iCkt\"{slR2K<-!");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(0, stringArray0.length);
      assertNotNull(menu0);
      
      int int0 = menu0.getOpcao();
      assertEquals((-1), menu0.getOpcao());
      assertEquals(0, stringArray0.length);
      assertEquals((-1), int0);
      
      // Undeclared exception!
      menu0.pedeTempo("t[G;");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[0] = "";
      stringArray0[1] = "AN;zo$!Qjds,wR";
      stringArray0[2] = "";
      stringArray0[3] = "";
      stringArray0[4] = "f! o74=JvG=nU$P1Z";
      stringArray0[5] = "";
      stringArray0[6] = "Op\u00E7\u00E3o: ";
      stringArray0[7] = "";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(8, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      menu0.pedeData("");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = ",I";
      stringArray0[1] = "nS";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(2, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      try { 
        menu0.pedeInt("-------------\n");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[7];
      stringArray0[0] = "";
      stringArray0[1] = ":k~!:pnqCe_, V";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(7, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = ",tH]";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(1, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "DV?V3RPxlW~KU";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(1, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      try { 
        menu0.pedeString("DV?V3RPxlW~KU");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String[] stringArray0 = new String[3];
      stringArray0[0] = "~IuI$j]";
      stringArray0[1] = "";
      stringArray0[2] = "";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(3, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      menu0.pedeTempo("");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "";
      stringArray0[1] = "Ogx!*knBu";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(2, stringArray0.length);
      assertNotNull(menu0);
      
      int int0 = menu0.getOpcao();
      assertEquals((-1), menu0.getOpcao());
      assertEquals(2, stringArray0.length);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[0] = "G7a3{=`ie7";
      stringArray0[1] = "?E";
      stringArray0[2] = "";
      stringArray0[3] = "";
      stringArray0[4] = "";
      stringArray0[5] = "";
      stringArray0[6] = "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
      stringArray0[7] = " ";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(8, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      try { 
        menu0.pedeDouble("a$Oty~<;[z?2xayJ%");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Menu menu0 = null;
      try {
        menu0 = new Menu((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[0] = "";
      stringArray0[1] = "y";
      stringArray0[2] = "FbRDB-2";
      stringArray0[3] = "";
      stringArray0[4] = "";
      stringArray0[5] = "";
      stringArray0[6] = "";
      stringArray0[7] = "";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(8, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      menu0.pedeDataHora("");
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(0, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      try { 
        menu0.pedeDouble("");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(0, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      menu0.pedeDataHora("dd/MM/yyyy");
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "w7:*kWj";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(1, stringArray0.length);
      assertNotNull(menu0);
      
      int int0 = menu0.getOpcao();
      assertEquals((-1), menu0.getOpcao());
      assertEquals(1, stringArray0.length);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(0, stringArray0.length);
      assertNotNull(menu0);
      
      int int0 = menu0.getOpcao();
      assertEquals((-1), menu0.getOpcao());
      assertEquals(0, stringArray0.length);
      assertEquals((-1), int0);
      
      // Undeclared exception!
      try { 
        menu0.pedeDouble("n|o=Mf\"9#+}");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      String[] stringArray0 = new String[2];
      String string0 = "$Dyjt!";
      SystemInUtil.addInputLine("$Dyjt!");
      stringArray0[0] = "$Dyjt!";
      String string1 = "oH_a'>W5X.SFFj_3%,h";
      stringArray0[1] = "oH_a'>W5X.SFFj_3%,h";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(2, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SystemInUtil.addInputLine(".4|");
      String[] stringArray0 = new String[4];
      stringArray0[0] = "72\"[ ";
      stringArray0[1] = "72\"[ ";
      stringArray0[2] = "72\"[ ";
      stringArray0[3] = "WcQ>ds-;m";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(4, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      try { 
        menu0.pedeDouble(": ");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "dd/MM/yyyy";
      stringArray0[1] = "";
      stringArray0[2] = "dd/MM/yyyy";
      stringArray0[3] = "~H-`saFwNv1t:Wp0t1";
      stringArray0[4] = "";
      stringArray0[5] = "Ff8Vve1Cg,<97";
      stringArray0[6] = "";
      stringArray0[7] = "";
      stringArray0[8] = "";
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      assertEquals(9, stringArray0.length);
      assertNotNull(menu0);
      
      // Undeclared exception!
      menu0.pedeTempo("");
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "p240bSw+KhU)8lE= ";
      stringArray0[1] = "-";
      stringArray0[2] = "Inserir uma dura\u00E7\u00E3o no formato horas:minutos ou horas:minutos:segundos";
      SystemInUtil.addInputLine("p240bSw+KhU)8lE= ");
      stringArray0[3] = "";
      stringArray0[4] = "[fx#dhC]Y;,5C*FI3l!";
      stringArray0[5] = "!#DT~";
      stringArray0[6] = "";
      stringArray0[7] = "612Nrvx%?#:b";
      stringArray0[8] = "6=U7=p't[8-g'";
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.pedeInt("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "";
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      menu0.pedeData("");
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[7] = "";
      stringArray0[2] = "";
      stringArray0[4] = "";
      stringArray0[5] = ":H7m";
      stringArray0[6] = "";
      stringArray0[0] = "Inserir uma dura\u00E7\u00E3o no formato horas:minutos ou horas:minutos:segundos";
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      menu0.pedeDataHora(":H7m");
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "Inserir um n\u00FAmero inteiro";
      SystemInUtil.addInputLine("Inserir um n\u00FAmero inteiro");
      stringArray0[4] = "a19'F#]p8pEP7";
      stringArray0[5] = "";
      stringArray0[6] = "";
      String string0 = "";
      stringArray0[7] = "";
      Menu menu0 = new Menu(stringArray0);
      String string1 = "";
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      String[] stringArray0 = new String[7];
      stringArray0[0] = "!<*OuTF";
      stringArray0[1] = "N2#o.x|mS_1|?~nWgDa";
      stringArray0[2] = "";
      SystemInUtil.addInputLine("");
      stringArray0[3] = "";
      stringArray0[4] = "Inserir data e hora no formato dia/m\u00EAs/ano horas:minutos:segundos";
      stringArray0[5] = "";
      stringArray0[6] = "fJ5eOVsv9N";
      Menu menu0 = new Menu(stringArray0);
      menu0.pedeString("");
      // Undeclared exception!
      try { 
        menu0.pedeDouble("N2#o.x|mS_1|?~nWgDa");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }
}
