/*
 * This file was automatically generated by EvoSuite
 * Wed May 28 22:13:42 GMT 2025
 */

package Projeto;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Projeto.UtilizadorPraticanteOcasional;
import java.time.LocalDate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UtilizadorPraticanteOcasional_ESTest extends UtilizadorPraticanteOcasional_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional();
      LocalDate localDate0 = MockLocalDate.now();
      // Undeclared exception!
      try { 
        utilizadorPraticanteOcasional0.utilizadorNumPeriodo((LocalDate) null, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // date
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("|T", "|T", "|T", 1904, 1904, 1904, (LocalDate) null, 'o');
      // Undeclared exception!
      try { 
        utilizadorPraticanteOcasional0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Utilizador", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("", (String) null, "", 1122, 0, (-2786), localDate0, 'y');
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional1 = null;
      try {
        utilizadorPraticanteOcasional1 = new UtilizadorPraticanteOcasional(utilizadorPraticanteOcasional0, (LocalDate) null, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // date
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = null;
      try {
        utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional((UtilizadorPraticanteOcasional) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Utilizador", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional1 = new UtilizadorPraticanteOcasional(utilizadorPraticanteOcasional0);
      assertEquals(1.25, utilizadorPraticanteOcasional1.getFatorMultiplicativo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("wYBp)1Bg\"@\"wD%=!1", "wYBp)1Bg\"@\"wD%=!1", "wYBp)1Bg\"@\"wD%=!1", (-292), (-292), (-292), localDate0, '-');
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional1 = new UtilizadorPraticanteOcasional(utilizadorPraticanteOcasional0, localDate0, localDate0);
      boolean boolean0 = utilizadorPraticanteOcasional1.equals(utilizadorPraticanteOcasional0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("wYBp)1Bg\"@\"wD%=!1", "wYBp)1Bg\"@\"wD%=!1", "wYBp)1Bg\"@\"wD%=!1", (-292), (-292), (-292), localDate0, '-');
      boolean boolean0 = utilizadorPraticanteOcasional0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional();
      boolean boolean0 = utilizadorPraticanteOcasional0.equals(utilizadorPraticanteOcasional0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional();
      boolean boolean0 = utilizadorPraticanteOcasional0.equals("Utilizador\nCodigo de Utilizador: 0\nNome: \nMorada: \nEmail: \nFrequencia Cardiaca: 0 bpm\nPeso: 0.0 kilos\nAltura: 0 centimetros\nData de nascimento 14/02/2014\nIdade: 0 anos\nGenero: \u0000\nAtividades: \n\nPlanos de treino: \n\nTipo de Utilizador: Praticante Ocasional\n");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("wYBp)1Bg\"@\"wD%=!1", "wYBp)1Bg\"@\"wD%=!1", "wYBp)1Bg\"@\"wD%=!1", (-292), (-292), (-292), localDate0, '-');
      String string0 = utilizadorPraticanteOcasional0.toString();
      assertEquals("Utilizador\nCodigo de Utilizador: 1\nNome: wYBp)1Bg\"@\"wD%=!1\nMorada: wYBp)1Bg\"@\"wD%=!1\nEmail: wYBp)1Bg\"@\"wD%=!1\nFrequencia Cardiaca: -292 bpm\nPeso: -292.0 kilos\nAltura: -292 centimetros\nData de nascimento 14/02/2014\nIdade: 0 anos\nGenero: -\nAtividades: \n\nPlanos de treino: \n\nTipo de Utilizador: Praticante Ocasional\n", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("wYBp)1Bg\"@\"wD%=!1", "wYBp)1Bg\"@\"wD%=!1", "wYBp)1Bg\"@\"wD%=!1", (-292), (-292), (-292), localDate0, '-');
      double double0 = utilizadorPraticanteOcasional0.getFatorMultiplicativo();
      assertEquals(1.25, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("wYBp)1Bg\"@\"w4D%=&!1", "wYBp)1Bg\"@\"w4D%=&!1", "wYBp)1Bg\"@\"w4D%=&!1", (-292), (-292), (-292), localDate0, '>');
      Object object0 = utilizadorPraticanteOcasional0.utilizadorNumPeriodo(localDate0, localDate0);
      assertNotSame(object0, utilizadorPraticanteOcasional0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("wYBp)1Bg\"@\"w4D%=&!1", "wYBp)1Bg\"@\"w4D%=&!1", "wYBp)1Bg\"@\"w4D%=&!1", (-292), (-292), (-292), localDate0, '>');
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional1 = new UtilizadorPraticanteOcasional(utilizadorPraticanteOcasional0, localDate0, localDate0);
      utilizadorPraticanteOcasional1.setDataNascimento((LocalDate) null);
      // Undeclared exception!
      try { 
        utilizadorPraticanteOcasional1.equals(utilizadorPraticanteOcasional0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Projeto.Utilizador", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("wYBp)1Bg\"@\"w4D%=&!1", "wYBp)1Bg\"@\"w4D%=&!1", "wYBp)1Bg\"@\"w4D%=&!1", (-292), (-292), (-292), localDate0, '>');
      Object object0 = utilizadorPraticanteOcasional0.clone();
      assertNotSame(object0, utilizadorPraticanteOcasional0);
  }
}
